// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meonsexfvlvqhsxotnbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lb25zZXhmdmx2cWhzeG90bmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTE5NDIsImV4cCI6MjA2Mzg4Nzk0Mn0.epLVh8x3GUrnI2cEc1HEsaFNnFcpYmlUsLIMJLqVllw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);